/* Lean Strength — נתוני התוכנית (שחר + בינה). מקור: LEAN_STRENGTH_SPEC.md */
window.LS_DATA = (function () {
  // ---------- שרירים (מפת השרירים, 15 תוויות) ----------
  var MUSCLES = [
    { k: 'delts', he: 'כתפיים', en: 'Deltoids', side: 'front' },
    { k: 'chest', he: 'חזה', en: 'Pectorals', side: 'front' },
    { k: 'biceps', he: 'יד קדמית', en: 'Biceps', side: 'front' },
    { k: 'abs', he: 'בטן', en: 'Abdominals', side: 'front' },
    { k: 'forearms', he: 'אמות', en: 'Forearms', side: 'front' },
    { k: 'quads', he: 'ארבע ראשי', en: 'Quadriceps', side: 'front' },
    { k: 'tibialis', he: 'שוקיים', en: 'Tibialis', side: 'front' },
    { k: 'traps', he: 'טרפז', en: 'Trapezius', side: 'back' },
    { k: 'rear_delts', he: 'כתף אחורית', en: 'Rear Delts', side: 'back' },
    { k: 'triceps', he: 'יד אחורית', en: 'Triceps', side: 'back' },
    { k: 'lats', he: 'גב רחב', en: 'Latissimus', side: 'back' },
    { k: 'lower_back', he: 'גב תחתון', en: 'Lower Back', side: 'back' },
    { k: 'glutes', he: 'ישבן', en: 'Glutes', side: 'back' },
    { k: 'hamstrings', he: 'מיתרי ברך', en: 'Hamstrings', side: 'back' },
    { k: 'calves', he: 'תאומים', en: 'Gastrocnemius', side: 'back' }
  ];

  // ---------- קטלוג תרגילים ----------
  // he/en, primary/assist (טקסט), mp/ma (מפתחות שרירים), why, steps, mistakes, tip, pose (שם קובץ איור), solo (איור יחיד), alts (חלופות)
  var EX = {
    bench_press: {
      he: 'לחיצת חזה במוט', en: 'Barbell Bench Press',
      primary: 'חזה', assist: 'כתף קדמית · יד אחורית', mp: ['chest'], ma: ['delts', 'triceps'],
      why: 'תרגיל הבסיס לחזה: מאפשר לעבוד עם משקל גבוה ולהתקדם ממנו שבוע אחר שבוע.',
      steps: ['שכבו על הספסל, כפות רגליים יציבות ברצפה, שכמות "נעוצות" אחורה ולמטה.', 'אחיזה מעט רחבה מהכתפיים. הורידו את המוט בשליטה לאמצע החזה.', 'דחפו מעלה ומעט אחורה עד לפשיטת מרפקים כמעט מלאה, בלי לנתק את הישבן מהספסל.'],
      mistakes: ['מרפקים פרושים ב-90° לצדדים — עומס על הכתף.', 'הקפצת המוט מהחזה.'],
      tip: 'דמיינו שאתם "מכופפים את המוט" — זה מנעל את השכמות ומגן על הכתפיים.',
      pose: 'bench_press', alts: ['db_bench_press', 'machine_chest_press', 'pushup']
    },
    incline_smith: {
      he: 'לחיצת חזה בשיפוע בסמית׳', en: 'Incline Smith Machine Press',
      primary: 'חזה עליון', assist: 'כתף קדמית · יד אחורית', mp: ['chest'], ma: ['delts', 'triceps'],
      why: 'שיפוע של 30° מעביר את העומס לחלק העליון של החזה — האזור שקובע "מדף" חזה מלא. הסמית׳ מאפשר להגיע קרוב לכשל בבטחה.',
      steps: ['כוונו ספסל לשיפוע 30–45° מתחת למוט, כך שהמוט יורד לחלק העליון של החזה.', 'הורידו בשליטה עד כמעט מגע, מרפקים בזווית ~45° לגוף.', 'דחפו מעלה עד פשיטה כמעט מלאה.'],
      mistakes: ['שיפוע גבוה מדי (60°+) — הופך לתרגיל כתפיים.', 'קימור גב מוגזם כדי "לקצר" את התנועה.'],
      tip: 'בסיום סט אפשר לנעול את המוט בכל נקודה — לכו קרוב לכשל בלי חשש.',
      pose: 'incline_smith', alts: ['incline_db_press', 'incline_machine_chest', 'kneeling_pushup']
    },
    cable_fly: {
      he: 'פרפר בכבלים', en: 'Cable Chest Fly',
      primary: 'חזה', assist: 'כתף קדמית', mp: ['chest'], ma: ['delts'],
      why: 'מתח רציף לאורך כל הטווח וכיווץ חזק בנקודת הסיום — משלים את הלחיצות הכבדות.',
      steps: ['עמדו במרכז בין הגלגלות, צעד קדימה, נטייה קלה קדימה, מרפקים כפופים מעט.', 'קרבו את הידיים בקשת עד שהן נפגשות מול החזה, וסחטו שנייה.', 'חזרו לאט עד מתיחה נעימה בחזה.'],
      mistakes: ['כיפוף מרפקים חזק — הופך את התנועה ללחיצה.', 'שימוש במומנטום מהגב.'],
      tip: 'חשבו על "לחבק עץ" — הידיים נעות בקשת, לא בקו ישר.',
      pose: 'cable_fly', alts: ['machine_chest_fly', 'db_fly', 'pec_deck']
    },
    overhead_press: {
      he: 'לחיצת כתפיים בישיבה עם משקולות', en: 'Seated Dumbbell Shoulder Press',
      primary: 'כתף קדמית ואמצעית', assist: 'יד אחורית · טרפז עליון', mp: ['delts'], ma: ['triceps', 'traps'],
      why: 'תרגיל הכוח המרכזי לכתפיים; המשקולות מאפשרות טווח טבעי לכל יד ומאזנות צדדים.',
      steps: ['גב נשען על משענת (~80°), משקולות בגובה האוזניים, מרפקים מעט לפני הגוף.', 'דחפו מעלה עד שהמשקולות נפגשות כמעט מעל הראש.', 'הורידו בשליטה עד שהמרפקים בגובה הכתף לפחות.'],
      mistakes: ['קימור גב תחתון וגלישה מהמשענת.', 'טווח קצר — עצירה גבוה מדי בירידה.'],
      tip: 'שאפו לפני הדחיפה ונשפו במעלה — הליבה מייצבת את הגו.',
      pose: 'overhead_press', alts: ['machine_shoulder_press', 'arnold_press', 'barbell_overhead_press']
    },
    pushdown: {
      he: 'פשיטת מרפק בכבל עם חבל', en: 'Rope Triceps Pushdown',
      primary: 'יד אחורית', assist: '', mp: ['triceps'], ma: [],
      why: 'בידוד נקי של היד האחורית; החבל מאפשר לפתוח את הידיים בסיום ולכווץ חזק את הראש החיצוני.',
      steps: ['מרפקים צמודים לגוף, גו נטוי מעט קדימה, אחיזת החבל בקצוות.', 'דחפו מטה עד פשיטה מלאה ופתחו את הידיים מעט לצדדים.', 'חזרו לאט עד שהאמות מקבילות לרצפה — המרפקים לא זזים.'],
      mistakes: ['מרפקים "מתעופפים" קדימה ומהכתפיים דוחפים.', 'משקל גבוה מדי שמכפיף את הגו.'],
      tip: 'המרפק הוא ציר — רק האמה זזה.',
      pose: 'pushdown', alts: ['straight_bar_pushdown', 'skull_crusher', 'dips_machine']
    },
    overhead_triceps: {
      he: 'פשיטת מרפק מעל הראש בכבל', en: 'Overhead Cable Triceps Extension',
      primary: 'יד אחורית (ראש ארוך)', assist: '', mp: ['triceps'], ma: [],
      why: 'כשהזרוע מעל הראש הראש הארוך של הטרייספס נמתח לגמרי — זה החלק שנותן ליד האחורית נפח ורוחב.',
      steps: ['גב לגלגלת, חבל מאחורי הראש, צעד קדימה ונטייה קלה של הגו.', 'פשטו את המרפקים קדימה ומעלה עד יישור מלא.', 'חזרו לאט עד מתיחה מלאה מאחורי הראש.'],
      mistakes: ['מרפקים שנפתחים לצדדים.', 'טווח קצר בפאזת המתיחה.'],
      tip: 'מרפקים צמודים לאוזניים לאורך כל התנועה.',
      pose: 'overhead_triceps', alts: ['db_overhead_extension', 'skull_crusher', 'pushdown']
    },
    pulldown: {
      he: 'משיכת פולי עליון אחיזה רחבה', en: 'Wide-Grip Lat Pulldown',
      primary: 'גב רחב', assist: 'יד קדמית · כתף אחורית', mp: ['lats'], ma: ['biceps', 'rear_delts'],
      why: 'התרגיל האפקטיבי ביותר לרוחב הגב — בונה את צורת ה-V.',
      steps: ['אחיזה רחבה מהכתפיים, ברכיים נעולות מתחת לריפוד, גו נטוי מעט אחורה.', 'משכו את המרפקים מטה ואחורה עד שהמוט מגיע לגובה עצם הבריח.', 'עלו לאט עד מתיחה מלאה של הגב — בלי להרים כתפיים.'],
      mistakes: ['משיכה עם הידיים (ביצפס) במקום עם המרפקים.', 'תנופה של הגו אחורה.'],
      tip: 'דמיינו שהידיים הן ווים — משכו מהמרפקים.',
      pose: 'pulldown', alts: ['assisted_pullup', 'close_grip_pulldown', 'straight_arm_pulldown']
    },
    seated_row: {
      he: 'חתירה בכבל בישיבה', en: 'Seated Cable Row',
      primary: 'גב אמצעי', assist: 'יד קדמית · כתף אחורית', mp: ['lats', 'traps'], ma: ['biceps', 'rear_delts'],
      why: 'מוסיף עובי לאמצע הגב ומאזן את כל הדחיפות של יום Push.',
      steps: ['ישיבה זקופה, ברכיים כפופות מעט, ידיות מול הבטן.', 'משכו את המרפקים אחורה וסחטו את השכמות זו לזו.', 'שחררו לאט קדימה עד מתיחה — הגו נשאר יציב.'],
      mistakes: ['נדנוד הגו קדימה-אחורה.', 'כתפיים שעולות לאוזניים.'],
      tip: 'חזה החוצה בסיום כל חזרה.',
      pose: 'seated_row', alts: ['chest_supported_row', 'one_arm_db_row', 'machine_row']
    },
    machine_row: {
      he: 'חתירה במכונה', en: 'Machine Row',
      primary: 'גב אמצעי', assist: 'יד קדמית · כתף אחורית', mp: ['lats', 'traps'], ma: ['biceps', 'rear_delts'],
      why: 'משענת החזה מנטרלת את הגב התחתון — כל העומס הולך לגב העליון, גם כשעייפים.',
      steps: ['כוונו את המושב כך שהידיות בגובה החזה התחתון.', 'משכו אחורה, מרפקים צמודים לגוף, סחטו את השכמות.', 'שחררו לאט לפשיטה מלאה.'],
      mistakes: ['התנתקות החזה מהמשענת.', 'טווח קצר בסוף הסט.'],
      tip: 'עצרו שנייה בכיווץ המלא.',
      pose: 'machine_row', alts: ['chest_supported_row', 'seated_row', 'one_arm_cable_row']
    },
    face_pull: {
      he: 'משיכת פנים בכבל', en: 'Cable Face Pull',
      primary: 'כתף אחורית', assist: 'טרפז אמצעי · גב עליון', mp: ['rear_delts'], ma: ['traps'],
      why: 'מחזק את הכתף האחורית ואת מסובבי הכתף — מגן על הכתפיים מכל הלחיצות ומשפר יציבה.',
      steps: ['גלגלת בגובה הפנים, חבל באחיזה עליונה, צעד אחורה.', 'משכו לכיוון הפנים כשהמרפקים גבוהים ופתוחים לצדדים.', 'בסיום — סובבו את האגודלים אחורה ("סובבו את הכתף החוצה").'],
      mistakes: ['משקל גבוה מדי — הופך למשיכה של הגב.', 'מרפקים שנופלים למטה.'],
      tip: 'זה תרגיל של איכות, לא של משקל. 15–20 חזרות נקיות.',
      pose: 'face_pull', alts: ['reverse_fly', 'band_pull_apart', 'rear_delt_db_fly']
    },
    preacher_curl: {
      he: 'כפיפת מרפק על ספסל סקוט', en: 'Preacher Curl',
      primary: 'יד קדמית', assist: 'אמות', mp: ['biceps'], ma: ['forearms'],
      why: 'הזרוע נעוצה בריפוד — אין דרך "לרמות" בתנופה, וה-ביצפס עובד לבד לאורך כל הטווח.',
      steps: ['בתי השחי נשענים על קצה הריפוד, זרועות מלאות על המשטח.', 'כפפו עד כיווץ מלא בלי להרים את המרפקים מהריפוד.', 'הורידו לאט עד כמעט פשיטה מלאה.'],
      mistakes: ['פשיטה מלאה בנעילה עם משקל כבד — עומס על הגיד.', 'הרמת הישבן מהמושב.'],
      tip: 'הפאזה השלילית (הירידה) היא החשובה — 3 שניות למטה.',
      pose: 'preacher_curl', alts: ['db_curl', 'incline_db_curl', 'cable_curl']
    },
    hammer_curl: {
      he: 'כפיפת פטיש', en: 'Hammer Curl',
      primary: 'יד קדמית · ברכיאליס', assist: 'אמות', mp: ['biceps', 'forearms'], ma: [],
      why: 'האחיזה הניטרלית מפעילה את הברכיאליס — השריר שמתחת לביצפס שמוסיף "גובה" לזרוע — ומחזק את האמות.',
      steps: ['משקולות לצדי הגוף, כפות ידיים פונות פנימה (כמו לתפוס פטיש).', 'כפפו עד גובה הכתף, מרפקים נשארים במקום.', 'הורידו בשליטה.'],
      mistakes: ['נדנוד הגוף.', 'סיבוב כף היד במהלך התנועה.'],
      tip: 'אפשר לסירוגין — יד אחר יד — כדי לשמור על ריכוז.',
      pose: 'hammer_curl', alts: ['rope_hammer_curl', 'reverse_curl', 'db_curl']
    },
    leg_press: {
      he: 'לחיצת רגליים במכונה', en: 'Leg Press',
      primary: 'ארבע ראשי', assist: 'ישבן · מקרבים', mp: ['quads'], ma: ['glutes'],
      why: 'מאפשר להעמיס את הרגליים במשקל גבוה בלי לטעון את הגב התחתון — בסיס יום הרגליים.',
      steps: ['כפות רגליים ברוחב כתפיים באמצע הפלטה, גב וישבן צמודים למושב.', 'הורידו עד שהברכיים ב-90° לפחות, בלי שהישבן מתרומם.', 'דחפו דרך כל כף הרגל עד כמעט פשיטה מלאה — אל תנעלו ברכיים.'],
      mistakes: ['נעילת ברכיים בסוף התנועה.', 'ישבן מתרומם מהמושב בתחתית.'],
      tip: 'שמרו על מגע רציף בין הגב התחתון למושב.',
      pose: 'leg_press', alts: ['hack_squat', 'goblet_squat', 'smith_squat']
    },
    leg_press_high: {
      he: 'לחיצת רגליים כפות גבוה ורחב', en: 'High & Wide Leg Press',
      primary: 'מיתרי ברך · ישבן', assist: 'ארבע ראשי', mp: ['hamstrings', 'glutes'], ma: ['quads'],
      why: 'אותה מכונה, מיקום כפות שונה: גבוה ורחב מעביר את העומס לישבן ולירך האחורית.',
      steps: ['כפות רגליים בחלק העליון של הפלטה, רחבות מהכתפיים, אצבעות מעט החוצה.', 'הורידו עמוק בשליטה עד לגבול הנוחות של האגן.', 'דחפו דרך העקבים.'],
      mistakes: ['ירידה עמוקה מדי שמרימה את האגן.', 'דחיפה מהאצבעות.'],
      tip: 'המשקל כאן נמוך יותר מלחיצה רגילה — וזה בסדר.',
      pose: 'leg_press_high', alts: ['rdl_db', 'hip_thrust', 'bulgarian_split_squat']
    },
    leg_extension: {
      he: 'פשיטת ברך במכונה', en: 'Leg Extension',
      primary: 'ארבע ראשי', assist: '', mp: ['quads'], ma: [],
      why: 'בידוד מלא של הארבע ראשי עם כיווץ חזק בנקודת הסיום — מה שהלחיצות לא מספקות.',
      steps: ['גב צמוד למשענת, ציר המכונה בקו הברך, ריפוד על הקרסוליים.', 'פשטו עד יישור מלא ועצרו שנייה.', 'הורידו לאט — לא לתת למשקל ליפול.'],
      mistakes: ['הקפצת המשקל בתחתית.', 'התרוממות מהמושב.'],
      tip: 'אצבעות רגליים מופנות מעט מעלה.',
      pose: 'leg_extension', alts: ['bulgarian_split_squat', 'goblet_squat', 'hack_squat']
    },
    leg_curl: {
      he: 'כפיפת ברך במכונה בשכיבה', en: 'Lying Leg Curl',
      primary: 'מיתרי ברך', assist: 'תאומים', mp: ['hamstrings'], ma: ['calves'],
      why: 'העבודה הישירה היחידה על מיתרי הברך דרך כפיפת ברך — חשוב לאיזון ברך בריאה.',
      steps: ['ריפוד ממש מעל העקבים, אגן צמוד לספסל.', 'כפפו עד שהעקבים קרובים לישבן.', 'הורידו לאט עד כמעט פשיטה מלאה.'],
      mistakes: ['אגן שמתרומם בכיפוף.', 'כפיפה מהירה מדי.'],
      tip: 'אפשר לכוון את האצבעות לעצמכם (Dorsiflexion) לבידוד טוב יותר של הירך האחורית.',
      pose: 'leg_curl', alts: ['seated_leg_curl', 'rdl_db', 'stability_ball_leg_curl']
    },
    calf_raise: {
      he: 'הרמת עקבים בעמידה', en: 'Standing Calf Raise',
      primary: 'תאומים', assist: 'סוליוס', mp: ['calves'], ma: [],
      why: 'ברגל ישרה התאומים (הגסטרוקנמיוס) עובדים במלואם — השריר שנותן צורה לשוק.',
      steps: ['קצות האצבעות על המדרגה, עקבים באוויר, ברכיים ישרות.', 'עלו כמה שיותר גבוה ועצרו שנייה למעלה.', 'הורידו לאט עד מתיחה מלאה מתחת לגובה המדרגה.'],
      mistakes: ['הקפצה בתחתית.', 'טווח חלקי למעלה.'],
      tip: 'שנייה למעלה, 2–3 שניות למטה — השוקיים מגיבים לטמפו.',
      pose: 'calf_raise', alts: ['seated_calf_raise', 'leg_press_calf', 'single_leg_calf_raise']
    },
    cable_crunch: {
      he: 'כפיפות בטן בכבל עם חבל', en: 'Cable Crunch',
      primary: 'בטן', assist: '', mp: ['abs'], ma: [],
      why: 'בטן היא שריר — היא צריכה התנגדות שאפשר להעלות, לא רק חזרות אינסופיות.',
      steps: ['על הברכיים מול הגלגלת, חבל לצדי הראש.', 'כפפו את הגו ("גלגלו" את הצלעות לאגן) בלי לזוז מהמותן.', 'עלו לאט עד מתיחה של הבטן.'],
      mistakes: ['משיכה עם הידיים.', 'תנועה מהמותן במקום מהגו.'],
      tip: 'המרפקים "מכוונים" לירכיים — הידיים רק מחזיקות.',
      pose: 'cable_crunch', alts: ['ab_crunch', 'decline_crunch', 'hanging_knee_raise']
    },
    cable_woodchopper: {
      he: 'סיבוב מותן בכבל', en: 'Cable Woodchopper',
      primary: 'שרירים אלכסוניים', assist: 'בטן · ליבה', mp: ['abs'], ma: [],
      why: 'תרגיל הסיבוב היחיד בתוכנית — מאמן את המלוכסנים ואת יציבות הגו בסיבוב.',
      steps: ['גלגלת גבוה, עמידה צידית לגלגלת, שתי ידיים על הידית.', 'סובבו את הגו מטה ובאלכסון לכיוון הברך הרחוקה — הזרועות ישרות.', 'חזרו בשליטה. סיימו את הסטים לצד אחד ואז החליפו.'],
      mistakes: ['סיבוב מהכתפיים בלבד.', 'כיפוף מרפקים.'],
      tip: 'הידיים הן מוט — הכוח מגיע מהגו.',
      pose: 'cable_woodchopper', solo: true, alts: ['pallof_press', 'russian_twist', 'side_plank']
    },
    standing_machine_lateral: {
      he: 'הרחקת כתפיים במכונה בעמידה', en: 'Standing Machine Lateral Raise',
      primary: 'כתף אמצעית', assist: 'טרפז עליון', mp: ['delts'], ma: ['traps'],
      why: 'הכתף האמצעית היא מה שנותן רוחב לפלג העליון. במכונה קל להישאר בטווח נכון ולהגיע קרוב לכשל.',
      steps: ['ריפוד על החלק העליון של הזרוע, מעל המרפק.', 'הרימו לצדדים עד גובה הכתף.', 'הורידו לאט — לא לתת למשקל ליפול.'],
      mistakes: ['הרמת הכתפיים לאוזניים.', 'עלייה מעל גובה הכתף.'],
      tip: 'חשבו על "לדחוף את המרפקים החוצה" ולא על להרים את הידיים.',
      pose: 'standing_machine_lateral', alts: ['db_lateral_raise', 'cable_lateral', 'machine_lateral']
    },
    cable_lateral: {
      he: 'הרחקת כתף בכבל', en: 'Cable Lateral Raise',
      primary: 'כתף אמצעית', assist: '', mp: ['delts'], ma: [],
      why: 'הכבל שומר על מתח גם בתחתית התנועה — שם המשקולות הרגילות "נחות".',
      steps: ['גלגלת נמוכה, צד לגלגלת, אחיזה ביד הרחוקה.', 'הרימו לצד עד גובה הכתף, מרפק כפוף מעט.', 'הורידו בשליטה.'],
      mistakes: ['נטיית גוף לכיוון הנגדי לצורך תנופה.', 'סיבוב הזרוע כך שהאגודל פונה מעלה.'],
      tip: 'זרת מעט גבוהה מהאגודל בסיום.',
      pose: 'cable_lateral', alts: ['db_lateral_raise', 'machine_lateral', 'standing_machine_lateral']
    },
    reverse_fly: {
      he: 'פרפר הפוך במכונה', en: 'Reverse Pec-Deck Fly',
      primary: 'כתף אחורית', assist: 'גב עליון · רומבואידים', mp: ['rear_delts'], ma: ['traps'],
      why: 'הכתף האחורית היא מה שגורם לכתף להיראות "עגולה" מהצד — ובד"כ מוזנחת.',
      steps: ['פנים למשענת, ידיות באחיזה ניטרלית, זרועות ישרות מעט כפופות.', 'פתחו לצדדים בקשת עד שהזרועות בקו הגוף.', 'חזרו לאט.'],
      mistakes: ['כיפוף מרפקים והפיכת התנועה לחתירה.', 'משקל גבוה מדי.'],
      tip: 'קלילות. 15–20 חזרות עם עצירה קצרה בסוף.',
      pose: 'reverse_fly', alts: ['face_pull', 'rear_delt_db_fly', 'band_pull_apart']
    },
    barbell_curl: {
      he: 'כפיפת מרפק במוט EZ', en: 'EZ-Bar Biceps Curl',
      primary: 'יד קדמית', assist: 'אמות', mp: ['biceps'], ma: ['forearms'],
      why: 'תרגיל הכוח לביצפס: כאן מעלים משקל לאורך זמן. המוט המזוגזג נוח למפרקי כף היד.',
      steps: ['עמידה יציבה, מרפקים לצדי הגוף.', 'כפפו עד כיווץ מלא בלי להזיז את המרפקים קדימה.', 'הורידו בשליטה עד פשיטה מלאה.'],
      mistakes: ['תנופה מהגב התחתון.', 'מרפקים שנעים קדימה — הכתף לוקחת.'],
      tip: 'הישענו קלות על קיר אם הגוף "מתנדנד".',
      pose: 'barbell_curl', alts: ['db_curl', 'cable_curl', 'preacher_curl']
    },
    behind_cable_lateral: {
      he: 'הרחקת כתף בכבל מאחורי הגב', en: 'Behind-the-Back Cable Lateral Raise',
      primary: 'כתף אמצעית', assist: '', mp: ['delts'], ma: [],
      why: 'הכבל מאחורי הגב משנה את זווית ההתנגדות ומדגיש את החלק האמצעי-האחורי של הכתף.',
      steps: ['גלגלת נמוכה, הכבל עובר מאחורי הגב ליד הרחוקה.', 'הרימו לצד ומעט קדימה עד גובה הכתף.', 'הורידו לאט.'],
      mistakes: ['תנופה מהגוף.', 'הרמת כתף לאוזן.'],
      tip: 'משתמש באותו איור של הרחקת כתף בכבל — הכבל פשוט עובר מאחור.',
      pose: 'cable_lateral', alts: ['cable_lateral', 'db_lateral_raise', 'machine_lateral']
    },
    cable_curl: {
      he: 'כפיפת מרפק בכבל', en: 'Cable Biceps Curl',
      primary: 'יד קדמית', assist: 'אמות', mp: ['biceps'], ma: ['forearms'],
      why: 'מתח רציף לאורך כל הטווח — משלים את תרגילי המשקולות החופשיות.',
      steps: ['גלגלת נמוכה, מוט ישר או EZ, מרפקים צמודים.', 'כפפו עד כיווץ מלא.', 'הורידו בשליטה עד פשיטה מלאה.'],
      mistakes: ['מרפקים שזזים קדימה.', 'תנופה.'],
      tip: 'צעד קטן אחורה מהגלגלת — כך יש מתח גם בתחתית.',
      pose: 'cable_curl', alts: ['db_curl', 'preacher_curl', 'hammer_curl']
    },
    machine_chest_fly: {
      he: 'פרפר במכונה', en: 'Machine Chest Fly (Pec-Deck)',
      primary: 'חזה', assist: 'כתף קדמית', mp: ['chest'], ma: ['delts'],
      why: 'מסלול מונחה ובטוח — מאפשר להגיע לכשל אמיתי בחזה בלי לדאוג ליציבות.',
      steps: ['כוונו את המושב כך שהידיות בגובה אמצע החזה.', 'קרבו את הידיות זו לזו בקשת, סחטו.', 'פתחו לאט עד מתיחה נעימה.'],
      mistakes: ['פתיחה רחבה מדי — עומס על הכתף.', 'הרמת הכתפיים.'],
      tip: 'שכמות צמודות למשענת כל הזמן.',
      pose: 'machine_chest_fly', alts: ['cable_fly', 'db_fly', 'machine_chest_press']
    },

    // ---- בינה (מפתחות ייחודיים לתוכנית שלה) ----
    hip_thrust: {
      he: 'הרמת אגן במכונה', en: 'Hip Thrust',
      primary: 'ישבן', assist: 'מיתרי ברך', mp: ['glutes'], ma: ['hamstrings'],
      why: 'תרגיל הישבן היעיל ביותר: כיווץ מלא בנקודת השיא ועומס ישיר על הגלוטאוס מקסימוס.',
      steps: ['גב עליון על הריפוד, כפות רגליים כך שבשיא הברכיים ב-90°.', 'דחפו את האגן מעלה עד שהגוף קו ישר מהברכיים לכתפיים.', 'סחטו את הישבן שנייה, והורידו בשליטה.'],
      mistakes: ['קימור גב תחתון בשיא — הסנטר לחזה עוזר.', 'דחיפה מהאצבעות במקום מהעקבים.'],
      tip: 'המבט קדימה (לא לתקרה) שומר על גב ניטרלי.',
      pose: 'hip_thrust', alts: ['glute_bridge', 'db_hip_thrust', 'cable_kickback']
    },
    incline_machine_chest: {
      he: 'לחיצת חזה בשיפוע במכונה', en: 'Incline Machine Chest Press',
      primary: 'חזה עליון', assist: 'כתף קדמית · יד אחורית', mp: ['chest'], ma: ['delts', 'triceps'],
      why: 'מחזקת ומרימה את החלק העליון של החזה — במכונה, עם מסלול בטוח ויציב.',
      steps: ['כוונו את המושב כך שהידיות בגובה החזה העליון.', 'דחפו קדימה ומעלה עד כמעט פשיטה מלאה.', 'חזרו לאט עד מתיחה קלה בחזה.'],
      mistakes: ['כתפיים שעולות קדימה.', 'טווח קצר.'],
      tip: 'שכמות "נעוצות" למשענת, חזה פתוח.',
      pose: 'incline_machine_chest', alts: ['incline_db_press', 'machine_chest_press', 'kneeling_pushup']
    },
    lat_pulldown: {
      he: 'משיכת פולי עליון במכונה', en: 'Lat Pulldown',
      primary: 'גב רחב', assist: 'יד קדמית · כתף אחורית', mp: ['lats'], ma: ['biceps', 'rear_delts'],
      why: 'מחזקת את הגב הרחב — משפר יציבה ונותן קו גב מחוטב.',
      steps: ['ברכיים מתחת לריפוד, אחיזה מעט רחבה מהכתפיים.', 'משכו את המרפקים מטה עד שהמוט בגובה עצם הבריח.', 'עלו לאט עד מתיחה מלאה.'],
      mistakes: ['משיכה מהידיים.', 'נדנוד הגו אחורה.'],
      tip: 'חשבו על להוריד את המרפקים לכיסים.',
      pose: 'lat_pulldown', alts: ['assisted_pullup', 'close_grip_pulldown', 'straight_arm_pulldown']
    },
    machine_lateral: {
      he: 'הרחקת כתפיים במכונה', en: 'Machine Lateral Raise',
      primary: 'כתף אמצעית', assist: 'טרפז עליון', mp: ['delts'], ma: ['traps'],
      why: 'כתפיים מעוצבות משדרות מראה חטוב — והמכונה עושה את זה בטוח ופשוט.',
      steps: ['ריפוד על הזרועות מעל המרפק.', 'הרימו לצדדים עד גובה הכתף.', 'הורידו לאט.'],
      mistakes: ['הרמת כתפיים לאוזניים.', 'משקל גבוה מדי ותנופה.'],
      tip: 'קל ונקי — 12–15 חזרות.',
      pose: 'machine_lateral', alts: ['db_lateral_raise', 'cable_lateral']
    },
    ab_crunch: {
      he: 'כפיפות בטן במכונה', en: 'Machine Ab Crunch',
      primary: 'בטן', assist: '', mp: ['abs'], ma: [],
      why: 'עבודה ישירה על הבטן עם התנגדות שאפשר להעלות בהדרגה.',
      steps: ['גב צמוד למשענת, ידיים על הידיות בלי למשוך.', 'כפפו את הגו — הצלעות לכיוון האגן.', 'חזרו לאט עד מתיחה.'],
      mistakes: ['משיכה מהידיים והצוואר.', 'תנועה מהמותן.'],
      tip: 'נשפו בכיווץ — הבטן מתכווצת חזק יותר.',
      pose: 'ab_crunch', alts: ['floor_crunch', 'cable_crunch', 'reverse_crunch']
    },
    lying_leg_curl: {
      he: 'כפיפת רגליים בשכיבה במכונה', en: 'Lying Leg Curl',
      primary: 'מיתרי ברך', assist: 'תאומים', mp: ['hamstrings'], ma: ['calves'],
      why: 'מחזקת את הירך האחורית — מחטב את הקו בין הישבן לברך ומגן על הברכיים.',
      steps: ['ריפוד מעל העקבים, אגן צמוד.', 'כפפו עד שהעקבים קרובים לישבן.', 'הורידו לאט.'],
      mistakes: ['אגן שמתרומם.', 'הורדה מהירה.'],
      tip: 'שתי שניות לפחות בירידה.',
      pose: 'lying_leg_curl', alts: ['seated_leg_curl', 'rdl_db', 'stability_ball_leg_curl']
    },
    seated_leg_curl: {
      he: 'כפיפת רגליים בישיבה במכונה', en: 'Seated Leg Curl',
      primary: 'מיתרי ברך', assist: 'תאומים', mp: ['hamstrings'], ma: ['calves'],
      why: 'בישיבה הירך האחורית מתוחה יותר — זווית שונה מהשכיבה, שמשלימה אותה.',
      steps: ['ריפוד עליון על הירכיים, ריפוד תחתון מעל העקבים.', 'כפפו את הברכיים מטה ואחורה עד כיווץ מלא.', 'חזרו לאט.'],
      mistakes: ['התרוממות מהמושב.', 'טווח חלקי.'],
      tip: 'רכנו מעט קדימה מהגו למתיחה טובה יותר.',
      pose: 'seated_leg_curl', alts: ['lying_leg_curl', 'rdl_db', 'glute_bridge']
    },
    pec_deck: {
      he: 'פרפר חזה במכונה', en: 'Pec-Deck Machine Fly',
      primary: 'חזה', assist: 'כתף קדמית', mp: ['chest'], ma: ['delts'],
      why: 'מחטב ומחזק את החזה בתנועת קירוב בטוחה ומונחית.',
      steps: ['ידיות בגובה אמצע החזה.', 'קרבו את הידיות בקשת עד שהן נפגשות.', 'פתחו לאט עד מתיחה נעימה.'],
      mistakes: ['פתיחה רחבה מדי.', 'הרמת הכתפיים.'],
      tip: 'סחטו שנייה במרכז.',
      pose: 'pec_deck', alts: ['cable_fly', 'db_fly', 'machine_chest_press']
    },
    seated_cable_row: {
      he: 'חתירה בכבל בישיבה', en: 'Seated Cable Row',
      primary: 'גב אמצעי', assist: 'יד קדמית · כתף אחורית', mp: ['lats', 'traps'], ma: ['biceps', 'rear_delts'],
      why: 'מחזקת את אמצע הגב ומשפרת יציבה — האיזון לכל תרגילי החזה.',
      steps: ['ישיבה זקופה, ברכיים כפופות מעט.', 'משכו את המרפקים אחורה וסחטו את השכמות.', 'שחררו לאט.'],
      mistakes: ['נדנוד הגו.', 'כתפיים לאוזניים.'],
      tip: 'חזה החוצה בסיום כל חזרה.',
      pose: 'seated_cable_row', alts: ['machine_row', 'chest_supported_row', 'one_arm_db_row']
    },
    hip_abduction: {
      he: 'הרחקת ירך במכונה', en: 'Hip Abduction Machine',
      primary: 'ישבן (גלוטאוס מדיוס)', assist: '', mp: ['glutes'], ma: [],
      why: 'הגלוטאוס מדיוס מעצב את צד הישבן ומייצב את האגן — חשוב גם לברכיים בריאות.',
      steps: ['ישיבה עם הגב צמוד, ריפוד מחוץ לברכיים.', 'פתחו את הרגליים לצדדים בשליטה.', 'סגרו לאט בלי לתת למשקל להתנגש.'],
      mistakes: ['פתיחה מהירה ותנופה.', 'התרוממות מהמושב.'],
      tip: 'נטייה קלה קדימה מגבירה את העבודה על הישבן.',
      pose: 'hip_abduction', alts: ['band_lateral_walk', 'side_lying_abduction', 'cable_hip_abduction']
    },
    machine_shoulder_press: {
      he: 'לחיצת כתפיים במכונה', en: 'Machine Shoulder Press',
      primary: 'כתפיים', assist: 'יד אחורית · חזה עליון', mp: ['delts'], ma: ['triceps', 'chest'],
      why: 'מחזקת את כל הכתף במסלול יציב — הבסיס לכתפיים חטובות.',
      steps: ['ידיות בגובה הכתפיים, גב צמוד.', 'דחפו מעלה עד כמעט פשיטה מלאה.', 'הורידו לאט עד גובה הכתף.'],
      mistakes: ['קימור גב.', 'טווח קצר.'],
      tip: 'נשפו בדחיפה.',
      pose: 'machine_shoulder_press', alts: ['overhead_press', 'arnold_press', 'pike_pushup']
    },
    woodchopper: {
      he: 'סיבוב מותן בכבל', en: 'Cable Woodchopper',
      primary: 'שרירים אלכסוניים', assist: 'בטן · ליבה', mp: ['abs'], ma: [],
      why: 'מחטב את המותן ומחזק את הליבה בתנועת סיבוב מבוקרת.',
      steps: ['גלגלת גבוה, עמידה צידית, שתי ידיים על הידית.', 'סובבו את הגו מטה ובאלכסון לכיוון הברך הרחוקה — זרועות ישרות.', 'חזרו בשליטה. סיימו צד ואז החליפו.'],
      mistakes: ['סיבוב מהכתפיים.', 'כיפוף מרפקים.'],
      tip: 'הידיים הן מוט — הכוח מהגו.',
      pose: 'woodchopper', solo: true, alts: ['pallof_press', 'russian_twist', 'side_plank']
    },

    // ---- חלופות (ללא כרטיס מלא) ----
    db_bench_press: { he: 'לחיצת חזה עם משקולות', en: 'Dumbbell Bench Press', primary: 'חזה', mp: ['chest'], ma: ['delts', 'triceps'] },
    machine_chest_press: { he: 'לחיצת חזה במכונה', en: 'Machine Chest Press', primary: 'חזה', mp: ['chest'], ma: ['delts', 'triceps'] },
    pushup: { he: 'שכיבות סמיכה', en: 'Push-up', primary: 'חזה', mp: ['chest'], ma: ['delts', 'triceps'] },
    kneeling_pushup: { he: 'שכיבות סמיכה על הברכיים', en: 'Knee Push-up', primary: 'חזה', mp: ['chest'], ma: ['delts', 'triceps'] },
    incline_db_press: { he: 'לחיצת חזה בשיפוע עם משקולות', en: 'Incline Dumbbell Press', primary: 'חזה עליון', mp: ['chest'], ma: ['delts', 'triceps'] },
    db_fly: { he: 'פרפר עם משקולות', en: 'Dumbbell Fly', primary: 'חזה', mp: ['chest'], ma: ['delts'] },
    arnold_press: { he: 'לחיצת ארנולד', en: 'Arnold Press', primary: 'כתפיים', mp: ['delts'], ma: ['triceps'] },
    barbell_overhead_press: { he: 'לחיצת כתפיים במוט בעמידה', en: 'Barbell Overhead Press', primary: 'כתפיים', mp: ['delts'], ma: ['triceps'] },
    straight_bar_pushdown: { he: 'פשיטת מרפק בכבל עם מוט ישר', en: 'Straight-Bar Triceps Pushdown', primary: 'יד אחורית', mp: ['triceps'], ma: [] },
    skull_crusher: { he: 'פשיטת מרפק בשכיבה (Skull Crusher)', en: 'Lying Triceps Extension', primary: 'יד אחורית', mp: ['triceps'], ma: [] },
    dips_machine: { he: 'מקבילים במכונה', en: 'Assisted / Machine Dip', primary: 'יד אחורית', mp: ['triceps'], ma: ['chest'] },
    db_overhead_extension: { he: 'פשיטת מרפק מעל הראש עם משקולת', en: 'Dumbbell Overhead Triceps Extension', primary: 'יד אחורית', mp: ['triceps'], ma: [] },
    bench_dip: { he: 'מקבילים על ספסל', en: 'Bench Dip', primary: 'יד אחורית', mp: ['triceps'], ma: ['chest'] },
    assisted_pullup: { he: 'מתח בעזרת מכונה', en: 'Assisted Pull-up', primary: 'גב רחב', mp: ['lats'], ma: ['biceps'] },
    close_grip_pulldown: { he: 'משיכת פולי עליון אחיזה צרה', en: 'Close-Grip Lat Pulldown', primary: 'גב רחב', mp: ['lats'], ma: ['biceps'] },
    straight_arm_pulldown: { he: 'משיכת פולי בזרועות ישרות', en: 'Straight-Arm Pulldown', primary: 'גב רחב', mp: ['lats'], ma: ['triceps'] },
    chest_supported_row: { he: 'חתירה עם משקולות על ספסל בשיפוע', en: 'Chest-Supported Dumbbell Row', primary: 'גב אמצעי', mp: ['lats', 'traps'], ma: ['biceps', 'rear_delts'] },
    one_arm_db_row: { he: 'חתירה עם משקולת ביד אחת', en: 'One-Arm Dumbbell Row', primary: 'גב אמצעי', mp: ['lats'], ma: ['biceps'] },
    one_arm_cable_row: { he: 'חתירה בכבל ביד אחת', en: 'One-Arm Cable Row', primary: 'גב אמצעי', mp: ['lats'], ma: ['biceps'] },
    band_pull_apart: { he: 'פתיחת גומייה', en: 'Band Pull-Apart', primary: 'כתף אחורית', mp: ['rear_delts'], ma: ['traps'] },
    rear_delt_db_fly: { he: 'פרפר הפוך עם משקולות', en: 'Bent-Over Rear Delt Raise', primary: 'כתף אחורית', mp: ['rear_delts'], ma: ['traps'] },
    db_curl: { he: 'כפיפת מרפק עם משקולות', en: 'Dumbbell Biceps Curl', primary: 'יד קדמית', mp: ['biceps'], ma: ['forearms'] },
    incline_db_curl: { he: 'כפיפת מרפק על ספסל בשיפוע', en: 'Incline Dumbbell Curl', primary: 'יד קדמית', mp: ['biceps'], ma: ['forearms'] },
    rope_hammer_curl: { he: 'כפיפת פטיש בכבל עם חבל', en: 'Rope Hammer Curl', primary: 'יד קדמית · ברכיאליס', mp: ['biceps', 'forearms'], ma: [] },
    reverse_curl: { he: 'כפיפת מרפק באחיזה הפוכה', en: 'Reverse Curl', primary: 'אמות · ברכיאליס', mp: ['forearms', 'biceps'], ma: [] },
    hack_squat: { he: 'האק סקוואט במכונה', en: 'Hack Squat', primary: 'ארבע ראשי', mp: ['quads'], ma: ['glutes'] },
    goblet_squat: { he: 'סקוואט גביע', en: 'Goblet Squat', primary: 'ארבע ראשי · ישבן', mp: ['quads', 'glutes'], ma: [] },
    smith_squat: { he: 'סקוואט בסמית׳', en: 'Smith Machine Squat', primary: 'ארבע ראשי · ישבן', mp: ['quads', 'glutes'], ma: [] },
    rdl_db: { he: 'דדליפט רומני עם משקולות', en: 'Dumbbell Romanian Deadlift', primary: 'מיתרי ברך · ישבן', mp: ['hamstrings', 'glutes'], ma: ['lower_back'] },
    bulgarian_split_squat: { he: 'סקוואט בולגרי', en: 'Bulgarian Split Squat', primary: 'ארבע ראשי · ישבן', mp: ['quads', 'glutes'], ma: [] },
    stability_ball_leg_curl: { he: 'כפיפת ברך על כדור פיזיו', en: 'Stability Ball Leg Curl', primary: 'מיתרי ברך', mp: ['hamstrings'], ma: ['glutes'] },
    step_up: { he: 'עלייה למדרגה עם משקולות', en: 'Dumbbell Step-up', primary: 'ארבע ראשי · ישבן', mp: ['quads', 'glutes'], ma: [] },
    seated_calf_raise: { he: 'הרמת עקבים בישיבה', en: 'Seated Calf Raise', primary: 'סוליוס · תאומים', mp: ['calves'], ma: [] },
    leg_press_calf: { he: 'הרמת עקבים על מכונת לחיצת רגליים', en: 'Leg Press Calf Raise', primary: 'תאומים', mp: ['calves'], ma: [] },
    single_leg_calf_raise: { he: 'הרמת עקב על רגל אחת', en: 'Single-Leg Calf Raise', primary: 'תאומים', mp: ['calves'], ma: [] },
    decline_crunch: { he: 'כפיפות בטן על ספסל בשיפוע', en: 'Decline Crunch', primary: 'בטן', mp: ['abs'], ma: [] },
    hanging_knee_raise: { he: 'הרמת ברכיים בתלייה', en: 'Hanging Knee Raise', primary: 'בטן', mp: ['abs'], ma: [] },
    floor_crunch: { he: 'כפיפות בטן על הרצפה', en: 'Crunch', primary: 'בטן', mp: ['abs'], ma: [] },
    reverse_crunch: { he: 'כפיפות בטן הפוכות', en: 'Reverse Crunch', primary: 'בטן', mp: ['abs'], ma: [] },
    dead_bug: { he: 'דד-באג', en: 'Dead Bug', primary: 'ליבה', mp: ['abs'], ma: [] },
    pallof_press: { he: 'לחיצת פאלוף', en: 'Pallof Press', primary: 'שרירים אלכסוניים · ליבה', mp: ['abs'], ma: [] },
    russian_twist: { he: 'סיבובי גו (Russian Twist)', en: 'Russian Twist', primary: 'שרירים אלכסוניים', mp: ['abs'], ma: [] },
    side_plank: { he: 'פלאנק צד', en: 'Side Plank', primary: 'שרירים אלכסוניים · ליבה', mp: ['abs'], ma: [] },
    db_lateral_raise: { he: 'הרחקת כתפיים עם משקולות', en: 'Dumbbell Lateral Raise', primary: 'כתף אמצעית', mp: ['delts'], ma: [] },
    glute_bridge: { he: 'גשר ישבן', en: 'Glute Bridge', primary: 'ישבן', mp: ['glutes'], ma: ['hamstrings'] },
    db_hip_thrust: { he: 'הרמת אגן עם משקולת', en: 'Dumbbell Hip Thrust', primary: 'ישבן', mp: ['glutes'], ma: ['hamstrings'] },
    cable_kickback: { he: 'בעיטה אחורה בכבל', en: 'Cable Glute Kickback', primary: 'ישבן', mp: ['glutes'], ma: ['hamstrings'] },
    band_lateral_walk: { he: 'הליכה צידית עם גומייה', en: 'Band Lateral Walk', primary: 'ישבן (מדיוס)', mp: ['glutes'], ma: [] },
    side_lying_abduction: { he: 'הרחקת ירך בשכיבה על הצד', en: 'Side-Lying Hip Abduction', primary: 'ישבן (מדיוס)', mp: ['glutes'], ma: [] },
    cable_hip_abduction: { he: 'הרחקת ירך בכבל בעמידה', en: 'Cable Hip Abduction', primary: 'ישבן (מדיוס)', mp: ['glutes'], ma: [] },
    pike_pushup: { he: 'שכיבות סמיכה בתנוחת פייק', en: 'Pike Push-up', primary: 'כתפיים', mp: ['delts'], ma: ['triceps'] }
  };

  // ---------- תוכניות ----------
  // items: [ex_id, sets, reps, rir, restSec, override?]
  var PROFILES = {
    shachar: {
      key: 'shachar', name: 'שחר', title: 'Lean Strength', accent: '#1E5FE0', accentSoft: '#EAF1FD', accentDark: '#6A9BF2', accentSoftDark: '#15233E',
      goal: 'חיטוב + בניית שריר', split: '5 ימי אימון · Push / Pull / Legs / כתפיים-ידיים / פלג עליון',
      rir: 'RIR 1–2', cardio: 'אירובי: לפי בחירה — לא הוגדר בתוכנית המקורית.',
      days: [
        { idx: 1, he: 'יום 1', name: 'דחיפה', en: 'Push', focus: 'חזה · כתפיים · יד אחורית',
          items: [['bench_press', 4, '6–10', 2, 150], ['incline_smith', 3, '8–12', 2, 120], ['cable_fly', 3, '12–15', 1, 90], ['overhead_press', 3, '8–12', 2, 120], ['pushdown', 3, '10–15', 1, 75], ['overhead_triceps', 3, '10–15', 1, 75]] },
        { idx: 2, he: 'יום 2', name: 'משיכה', en: 'Pull', focus: 'גב · יד קדמית · כתף אחורית',
          items: [['pulldown', 4, '8–12', 2, 120], ['seated_row', 3, '8–12', 2, 120], ['machine_row', 3, '10–12', 2, 90], ['face_pull', 3, '15–20', 1, 75], ['preacher_curl', 3, '10–12', 1, 75], ['hammer_curl', 3, '10–12', 1, 75]] },
        { idx: 3, he: 'יום 3', name: 'רגליים', en: 'Legs', focus: 'ארבע ראשי · מיתרי ברך · שוקיים · ליבה',
          items: [['leg_press', 4, '10–15', 2, 150], ['leg_press_high', 3, '10–15', 2, 150], ['leg_extension', 3, '12–15', 1, 90], ['leg_curl', 3, '10–15', 1, 90], ['calf_raise', 4, '12–20', 1, 60], ['cable_crunch', 3, '12–15', 1, 60], ['cable_woodchopper', 3, '12–15', 1, 60]] },
        { idx: 5, he: 'יום 5', name: 'כתפיים וידיים', en: 'Shoulders & Arms', focus: 'כתף אמצעית · כתף אחורית · ידיים',
          items: [['overhead_press', 4, '8–12', 2, 120], ['standing_machine_lateral', 4, '12–20', 1, 60], ['cable_lateral', 3, '12–15', 1, 60], ['reverse_fly', 3, '15–20', 1, 60], ['barbell_curl', 3, '8–12', 1, 90], ['pushdown', 3, '10–15', 1, 75]] },
        { idx: 6, he: 'יום 6', name: 'פלג גוף עליון', en: 'Upper Aesthetic', focus: 'חזה · גב · כתפיים · ידיים',
          items: [['machine_chest_fly', 4, '10–15', 2, 90], ['pulldown', 4, '8–12', 2, 120], ['cable_fly', 3, '12–15', 1, 75], ['behind_cable_lateral', 4, '12–20', 1, 60], ['cable_curl', 3, '10–15', 1, 75], ['overhead_triceps', 3, '10–15', 1, 75]] }
      ],
      // סדר שבועי (7 תאים): מפתח יום או null למנוחה
      week: [1, 2, 3, null, 5, 6, null],
      groups: [
        { he: 'חזה', ex: ['bench_press', 'incline_smith', 'cable_fly', 'machine_chest_fly'] },
        { he: 'גב', ex: ['pulldown', 'seated_row', 'machine_row'] },
        { he: 'כתפיים', ex: ['overhead_press', 'standing_machine_lateral', 'cable_lateral', 'behind_cable_lateral'] },
        { he: 'כתף אחורית', ex: ['face_pull', 'reverse_fly'] },
        { he: 'יד קדמית', ex: ['preacher_curl', 'hammer_curl', 'barbell_curl', 'cable_curl'] },
        { he: 'יד אחורית', ex: ['pushdown', 'overhead_triceps'] },
        { he: 'רגליים', ex: ['leg_press', 'leg_press_high', 'leg_extension', 'leg_curl', 'calf_raise'] },
        { he: 'ליבה', ex: ['cable_crunch', 'cable_woodchopper'] }
      ],
      coverage: 'שרירים שמאומנים חלקית בתוכנית: גב תחתון / זוקפי עמוד השדרה (הפער העיקרי), סוליוס (הרמת עקב בעמידה מדגישה גסטרוקנמיוס), אמות/אחיזה (רק עקיף), צוואר.'
    },
    bina: {
      key: 'bina', name: 'בינה', title: 'Lean Strength', accent: '#4F8DF5', accentSoft: '#EAF2FE', accentDark: '#86B2F8', accentSoftDark: '#172A47',
      goal: 'ירידת שומן + חיזוק', split: '3 אימוני Full Body (A/B/C) · דגש ישבן · בטן · חזה',
      rir: 'RIR 2 (רחוק מכשל)', cardio: '30 דק׳ אירובי אחרי כל אימון.',
      days: [
        { idx: 'A', he: 'אימון A', name: 'ישבן וחזה', en: 'Full Body A', focus: 'ישבן · חזה · גב · כתפיים · בטן',
          items: [['leg_press', 3, '10–15', 2, 120, { primary: 'ארבע ראשי · ישבן', assist: 'מיתרי ברך' }], ['hip_thrust', 3, '10–15', 2, 120], ['incline_machine_chest', 3, '10–15', 2, 90], ['lat_pulldown', 3, '10–15', 2, 90], ['machine_lateral', 3, '12–15', 2, 60], ['ab_crunch', 3, '12–15', 2, 60]] },
        { idx: 'B', he: 'אימון B', name: 'רגליים אחוריות ובטן', en: 'Full Body B', focus: 'מיתרי ברך · חזה · גב · ידיים · בטן',
          items: [['lying_leg_curl', 3, '10–15', 2, 90], ['seated_leg_curl', 3, '10–15', 2, 90], ['pec_deck', 3, '12–15', 2, 75], ['seated_cable_row', 3, '10–15', 2, 90], ['cable_curl', 3, '10–15', 2, 60], ['cable_crunch', 3, '12–15', 2, 60, { he: 'כפיפת בטן בכבל' }]] },
        { idx: 'C', he: 'אימון C', name: 'ישבן וכתפיים', en: 'Full Body C', focus: 'ישבן · חזה · כתפיים · יד אחורית · ליבה',
          items: [['hip_abduction', 3, '12–15', 2, 60], ['leg_press_high', 3, '10–15', 2, 120, { primary: 'ישבן · מיתרי ברך', assist: 'ארבע ראשי' }], ['incline_machine_chest', 3, '10–15', 2, 90], ['machine_shoulder_press', 3, '10–15', 2, 90], ['pushdown', 3, '12–15', 2, 60, { he: 'פשיטת מרפק בכבל', en: 'Cable Triceps Pushdown' }], ['woodchopper', 3, '12–15', 2, 60]] }
      ],
      week: ['A', null, 'B', null, 'C', null, null],
      groups: [
        { he: 'ישבן', ex: ['hip_thrust', 'hip_abduction', 'leg_press_high'] },
        { he: 'רגליים', ex: ['leg_press', 'lying_leg_curl', 'seated_leg_curl'] },
        { he: 'חזה', ex: ['incline_machine_chest', 'pec_deck'] },
        { he: 'גב', ex: ['lat_pulldown', 'seated_cable_row'] },
        { he: 'כתפיים', ex: ['machine_lateral', 'machine_shoulder_press'] },
        { he: 'יד קדמית', ex: ['cable_curl'] },
        { he: 'יד אחורית', ex: ['pushdown'] },
        { he: 'בטן / ליבה', ex: ['ab_crunch', 'cable_crunch', 'woodchopper'] }
      ],
      coverage: 'תוכנית מתחילה ב-3 אימונים: הנפח לכל קבוצה נמוך בכוונה. כשהטכניקה יציבה — מוסיפים סט לתרגילי הישבן/חזה לפני שמוסיפים תרגילים.'
    }
  };

  var GLOSSARY = [
    { t: 'RIR', d: 'Reps In Reserve — כמה חזרות נשארו "במאגר" לפני כשל. RIR 2 = עצרתם כשיכולתם לעשות עוד 2 חזרות נקיות.' },
    { t: 'סט / חזרה', d: 'חזרה = ביצוע אחד מלא של התנועה. סט = רצף חזרות עד מנוחה.' },
    { t: 'נפח', d: 'סך הסטים לקבוצת שריר בשבוע. 10–20 סטים/שבוע לקבוצה הוא הטווח היעיל; מתחת ל-10 גירוי חלקי, מעל ~20 תשואה פוחתת.' },
    { t: 'פרוגרסיה', d: 'הוספת חזרה או משקל מאימון לאימון. הגעתם לקצה טווח החזרות בטכניקה נקייה? העלו משקל בפעם הבאה.' },
    { t: 'טווח תנועה', d: 'מרחק התנועה המלא של המפרק בתרגיל. טווח מלא ומבוקר עדיף על משקל גבוה בטווח חלקי.' },
    { t: 'חימום', d: '5 דק׳ אירובי קל + 1–2 סטים קלים של התרגיל הראשון לפני סטי העבודה.' },
    { t: 'ליבה (Core)', d: 'השרירים שמייצבים את הגו, עמוד השדרה והאגן: בטן ישרה, מלוכסנים, בטן רוחבית וזוקפי הגב. תרגיל ליבה מאמן ייצוב, כיפוף או סיבוב של הגו עצמו — בשונה מתרגיל שמניע גפה.' },
    { t: 'Full Body', d: 'אימון שמכסה את כל הגוף בפעם אחת — מתאים ל-3 אימונים בשבוע.' }
  ];

  var FAQ = [
    { q: 'המכונה תפוסה או לא קיימת בחדר הכושר — מה עושים?', a: 'פותחים את "חלופות" בכרטיס התרגיל ובוחרים תרגיל לאותו שריר. אפשר גם להחליף לצמיתות בלחיצה על "החלף" — הלוג יעקוב אחרי התרגיל החדש.' },
    { q: 'מתי להעלות משקל?', a: 'כשמסיימים את כל הסטים בקצה העליון של טווח החזרות, בטכניקה נקייה וב-RIR שנקבע. העלו 2.5–5% ותחזרו לתחתית הטווח.' },
    { q: 'מה זה RIR 2 בפועל?', a: 'לעצור את הסט כשמרגישים שיש עוד 2 חזרות טובות בכוח. זה מרגיש "קשה אבל שולט" — לא רעידות ולא טכניקה שמתפרקת.' },
    { q: 'פספסתי אימון — לדחוף הכול לשבוע הבא?', a: 'לא. ממשיכים מהאימון הבא בתור. השבוע פשוט "מתגלגל" קדימה.' },
    { q: 'כמה מנוחה בין סטים?', a: 'לפי הצ׳יפ בכל תרגיל: תרגילים כבדים (לחיצות, לחיצת רגליים) 2–3 דק׳; תרגילי בידוד 60–90 שנ׳. הטיימר בתחתית המסך מתחיל לבד בסימון סט.' },
    { q: 'מה זה ליבה ולמה יש רק תרגיל אחד-שניים?', a: 'הליבה (בטן, מלוכסנים, גב תחתון) עובדת כמייצבת ברוב התרגילים הגדולים. תרגילי הבטן הישירים משלימים את זה — לא צריך יותר.' },
    { q: 'אפשר לשנות את סדר התרגילים?', a: 'עדיף לשמור: התרגילים הכבדים ראשונים כשיש כוח, הבידוד בסוף. אם מכונה תפוסה — אפשר להחליף בין תרגילים סמוכים.' }
  ];

  var LINKS = {
  "bench_press": "https://musclewiki.com/exercise/barbell-bench-press",
  "incline_smith": "https://musclewiki.com/exercise/smith-machine-incline-bench-press",
  "cable_fly": "https://musclewiki.com/exercise/cable-pec-fly",
  "overhead_press": "https://musclewiki.com/exercise/dumbbell-seated-overhead-press",
  "pushdown": "https://musclewiki.com/exercise/cable-rope-pushdown",
  "overhead_triceps": "https://musclewiki.com/exercise/cable-rope-overhead-tricep-extension",
  "pulldown": "https://musclewiki.com/exercise/cable-lat-pulldown",
  "seated_row": "https://musclewiki.com/exercise/machine-seated-cable-row",
  "machine_row": "https://musclewiki.com/exercise/machine-plate-loaded-row",
  "face_pull": "https://musclewiki.com/exercise/machine-face-pulls",
  "preacher_curl": "https://musclewiki.com/exercise/ez-bar-preacher-curl",
  "hammer_curl": "https://musclewiki.com/exercise/dumbbell-hammer-curl",
  "leg_press": "https://musclewiki.com/exercise/machine-leg-press",
  "leg_press_high": "https://musclewiki.com/exercise/machine-leg-press",
  "leg_extension": "https://musclewiki.com/exercise/machine-leg-extension",
  "leg_curl": "https://musclewiki.com/exercise/machine-hamstring-curl",
  "calf_raise": "https://musclewiki.com/exercise/machine-standing-calf-raises",
  "cable_crunch": "https://musclewiki.com/exercise/cable-rope-kneeling-crunch",
  "cable_woodchopper": "https://musclewiki.com/exercise/cable-wood-chopper",
  "standing_machine_lateral": "https://musclewiki.com/exercise/machine-standing-lateral-raise",
  "cable_lateral": "https://musclewiki.com/exercise/cable-low-single-arm-lateral-raise",
  "reverse_fly": "https://musclewiki.com/exercise/machine-reverse-fly",
  "barbell_curl": "https://musclewiki.com/exercise/ez-bar-curl",
  "behind_cable_lateral": "https://musclewiki.com/exercise/cable-behind-the-back-lateral-raise",
  "cable_curl": "https://musclewiki.com/exercise/cable-bar-curl",
  "machine_chest_fly": "https://musclewiki.com/exercise/machine-pec-fly",
  "hip_thrust": "https://musclewiki.com/exercise/barbell-hip-thrust",
  "incline_machine_chest": "https://musclewiki.com/exercise/machine-plate-loaded-incline-chest-press",
  "lat_pulldown": "https://musclewiki.com/exercise/cable-lat-pulldown",
  "machine_lateral": "https://www.strengthlog.com/machine-lateral-raise/",
  "ab_crunch": "https://musclewiki.com/exercise/machine-crunch",
  "lying_leg_curl": "https://musclewiki.com/exercise/machine-hamstring-curl",
  "seated_leg_curl": "https://musclewiki.com/exercise/machine-seated-leg-curl",
  "pec_deck": "https://musclewiki.com/exercise/machine-pec-fly",
  "seated_cable_row": "https://musclewiki.com/exercise/machine-seated-cable-row",
  "hip_abduction": "https://musclewiki.com/exercise/machine-hip-abduction",
  "machine_shoulder_press": "https://musclewiki.com/exercise/machine-overhand-overhead-press",
  "woodchopper": "https://musclewiki.com/exercise/cable-wood-chopper",
  "db_bench_press": "https://musclewiki.com/exercise/dumbbell-bench-press",
  "machine_chest_press": "https://musclewiki.com/exercise/machine-chest-press",
  "pushup": "https://musclewiki.com/exercise/push-up",
  "kneeling_pushup": "https://musclewiki.com/exercise/bodyweight-knee-push-ups",
  "incline_db_press": "https://musclewiki.com/exercise/dumbbell-incline-bench-press",
  "db_fly": "https://musclewiki.com/exercise/dumbbell-chest-fly",
  "arnold_press": "https://musclewiki.com/exercise/dumbbell-arnold-press",
  "barbell_overhead_press": "https://musclewiki.com/exercise/barbell-overhead-press",
  "straight_bar_pushdown": "https://musclewiki.com/exercise/cable-bar-pushdown",
  "skull_crusher": "https://musclewiki.com/exercise/barbell-skullcrusher",
  "dips_machine": "https://musclewiki.com/exercise/machine-assisted-parallel-bar-dips",
  "db_overhead_extension": "https://musclewiki.com/exercise/dumbbell-overhead-tricep-extension",
  "bench_dip": "https://musclewiki.com/exercise/bench-dips",
  "assisted_pullup": "https://musclewiki.com/exercise/machine-assisted-pull-up",
  "close_grip_pulldown": "https://musclewiki.com/exercise/neutral-pulldown",
  "straight_arm_pulldown": "https://musclewiki.com/exercise/cable-straight-arm-pulldown",
  "chest_supported_row": "https://musclewiki.com/exercise/dumbbell-laying-incline-row",
  "one_arm_db_row": "https://musclewiki.com/exercise/dumbbell-single-arm-row",
  "one_arm_cable_row": "https://musclewiki.com/exercise/cable-single-arm-neutral-grip-row",
  "band_pull_apart": "https://musclewiki.com/exercise/band-pull-apart",
  "rear_delt_db_fly": "https://musclewiki.com/exercise/dumbbell-rear-delt-fly",
  "db_curl": "https://musclewiki.com/exercise/dumbbell-curl",
  "incline_db_curl": "https://musclewiki.com/exercise/dumbbell-incline-curl",
  "rope_hammer_curl": "https://musclewiki.com/exercise/cable-rope-hammer-curl",
  "reverse_curl": "https://musclewiki.com/exercise/barbell-reverse-curl",
  "hack_squat": "https://musclewiki.com/exercise/machine-hack-squat",
  "goblet_squat": "https://musclewiki.com/exercise/dumbbell-goblet-squat",
  "smith_squat": "https://musclewiki.com/exercise/smith-machine-squat",
  "rdl_db": "https://musclewiki.com/exercise/dumbbell-romanian-deadlift",
  "bulgarian_split_squat": "https://musclewiki.com/exercise/dumbbell-bulgarian-split-squat",
  "stability_ball_leg_curl": "https://musclewiki.com/exercise/stability-ball-hamstring-curl",
  "step_up": "https://musclewiki.com/exercise/dumbbell-step-up",
  "seated_calf_raise": "https://musclewiki.com/exercise/machine-seated-calf-raises",
  "leg_press_calf": "https://musclewiki.com/exercise/machine-horizontal-leg-press-calf-raise",
  "single_leg_calf_raise": "https://musclewiki.com/exercise/bodyweight-single-leg-calf-raise",
  "decline_crunch": "https://www.hevyapp.com/exercises/how-to-decline-crunch/",
  "hanging_knee_raise": "https://musclewiki.com/exercise/hanging-knee-raises",
  "floor_crunch": "https://musclewiki.com/exercise/crunches",
  "reverse_crunch": "https://musclewiki.com/exercise/reverse-crunch",
  "dead_bug": "https://musclewiki.com/exercise/dead-bug",
  "pallof_press": "https://musclewiki.com/exercise/cable-pallof-press",
  "russian_twist": "https://musclewiki.com/exercise/bodyweight-russian-twist",
  "side_plank": "https://musclewiki.com/exercise/elbow-side-plank",
  "db_lateral_raise": "https://musclewiki.com/exercise/dumbbell-lateral-raise",
  "glute_bridge": "https://musclewiki.com/exercise/glute-bridge",
  "db_hip_thrust": "https://musclewiki.com/exercise/dumbbell-hip-thrust",
  "cable_kickback": "https://musclewiki.com/exercise/cable-standing-glute-kickback",
  "band_lateral_walk": "https://musclewiki.com/exercise/side-walks-resisted",
  "side_lying_abduction": "https://musclewiki.com/exercise/abductor-leg-raise-side-lying",
  "cable_hip_abduction": "https://musclewiki.com/exercise/cable-standing-hip-abduction",
  "pike_pushup": "https://musclewiki.com/exercise/bodyweight-pike-press"
};

  // איורים: תרגיל -> שם קובץ ב-figs/ (מקור: free-exercise-db, נחלת הכלל)
  var FIGS = {
  "bench_press": "Barbell_Bench_Press_-_Medium_Grip",
  "incline_smith": "Smith_Machine_Incline_Bench_Press",
  "cable_fly": "Cable_Crossover",
  "overhead_press": "Dumbbell_Shoulder_Press",
  "pushdown": "Triceps_Pushdown_-_Rope_Attachment",
  "overhead_triceps": "Cable_Rope_Overhead_Triceps_Extension",
  "pulldown": "Wide-Grip_Lat_Pulldown",
  "seated_row": "Seated_Cable_Rows",
  "machine_row": "Leverage_Iso_Row",
  "face_pull": "Face_Pull",
  "preacher_curl": "Preacher_Curl",
  "hammer_curl": "Hammer_Curls",
  "leg_press": "Leg_Press",
  "leg_press_high": "Leg_Press",
  "leg_extension": "Leg_Extensions",
  "leg_curl": "Lying_Leg_Curls",
  "calf_raise": "Standing_Calf_Raises",
  "cable_crunch": "Cable_Crunch",
  "cable_woodchopper": "Standing_Cable_Wood_Chop",
  "standing_machine_lateral": "Side_Lateral_Raise",
  "cable_lateral": "Cable_Seated_Lateral_Raise",
  "reverse_fly": "Reverse_Machine_Flyes",
  "barbell_curl": "EZ-Bar_Curl",
  "behind_cable_lateral": "Cable_Seated_Lateral_Raise",
  "cable_curl": "Standing_Biceps_Cable_Curl",
  "machine_chest_fly": "Butterfly",
  "hip_thrust": "Barbell_Hip_Thrust",
  "incline_machine_chest": "Leverage_Incline_Chest_Press",
  "lat_pulldown": "Wide-Grip_Lat_Pulldown",
  "machine_lateral": "Seated_Side_Lateral_Raise",
  "ab_crunch": "Ab_Crunch_Machine",
  "lying_leg_curl": "Lying_Leg_Curls",
  "seated_leg_curl": "Seated_Leg_Curl",
  "pec_deck": "Butterfly",
  "seated_cable_row": "Seated_Cable_Rows",
  "hip_abduction": "Thigh_Abductor",
  "machine_shoulder_press": "Leverage_Shoulder_Press",
  "woodchopper": "Standing_Cable_Wood_Chop",
  "db_bench_press": "Dumbbell_Bench_Press",
  "machine_chest_press": "Leverage_Chest_Press",
  "pushup": "Pushups",
  "kneeling_pushup": "Incline_Push-Up_Medium",
  "incline_db_press": "Incline_Dumbbell_Press",
  "db_fly": "Dumbbell_Flyes",
  "arnold_press": "Arnold_Dumbbell_Press",
  "barbell_overhead_press": "Standing_Military_Press",
  "straight_bar_pushdown": "Triceps_Pushdown",
  "skull_crusher": "EZ-Bar_Skullcrusher",
  "dips_machine": "Dip_Machine",
  "db_overhead_extension": "Standing_Dumbbell_Triceps_Extension",
  "bench_dip": "Bench_Dips",
  "assisted_pullup": "Band_Assisted_Pull-Up",
  "close_grip_pulldown": "Close-Grip_Front_Lat_Pulldown",
  "straight_arm_pulldown": "Straight-Arm_Pulldown",
  "chest_supported_row": "Dumbbell_Incline_Row",
  "one_arm_db_row": "One-Arm_Dumbbell_Row",
  "one_arm_cable_row": "Seated_One-arm_Cable_Pulley_Rows",
  "band_pull_apart": "Band_Pull_Apart",
  "rear_delt_db_fly": "Reverse_Flyes",
  "db_curl": "Dumbbell_Bicep_Curl",
  "incline_db_curl": "Incline_Dumbbell_Curl",
  "rope_hammer_curl": "Cable_Hammer_Curls_-_Rope_Attachment",
  "reverse_curl": "Reverse_Barbell_Curl",
  "hack_squat": "Hack_Squat",
  "goblet_squat": "Goblet_Squat",
  "smith_squat": "Smith_Machine_Squat",
  "rdl_db": "Stiff-Legged_Dumbbell_Deadlift",
  "bulgarian_split_squat": "Split_Squat_with_Dumbbells",
  "stability_ball_leg_curl": "Ball_Leg_Curl",
  "step_up": "Dumbbell_Step_Ups",
  "seated_calf_raise": "Seated_Calf_Raise",
  "leg_press_calf": "Calf_Press_On_The_Leg_Press_Machine",
  "single_leg_calf_raise": "Dumbbell_Seated_One-Leg_Calf_Raise",
  "decline_crunch": "Decline_Crunch",
  "hanging_knee_raise": "Hanging_Leg_Raise",
  "floor_crunch": "Crunches",
  "reverse_crunch": "Reverse_Crunch",
  "dead_bug": "Dead_Bug",
  "pallof_press": "Pallof_Press",
  "russian_twist": "Russian_Twist",
  "side_plank": "Side_Bridge",
  "db_lateral_raise": "Side_Lateral_Raise",
  "glute_bridge": "Butt_Lift_Bridge",
  "db_hip_thrust": "Barbell_Hip_Thrust",
  "cable_kickback": "One-Legged_Cable_Kickback",
  "band_lateral_walk": "Monster_Walk",
  "side_lying_abduction": "Side_Leg_Raises",
  "cable_hip_abduction": "Thigh_Abductor",
  "pike_pushup": "Decline_Push-Up"
};

  return { MUSCLES: MUSCLES, EX: EX, PROFILES: PROFILES, GLOSSARY: GLOSSARY, FAQ: FAQ, LINKS: LINKS, FIGS: FIGS };
})();
